main: fr.xamez.cite_quest_core.CiteQuestCore
name: Cite-quest-core
version: 1.1
author: Xamez
api-version: 1.16
depend:
  - Cite-libs
  - Cite-core
  - Citizens
commands:
  quest:
    description: Ouvre l'interface des quêtes
    aliases: [q, quete]
  tcc: